#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use function Differ\Differ\genDiff;

$doc = <<<DOC
Generate diff

Usage:
  gendiff (-h | --help)
  gendiff (-v | --version)
  gendiff [--format <fmt>] <firstFile> <secondFile>

Options:
  -h --help         Show this screen
  -v --version      Show version
  --format <fmt>    Report format [default: stylish]
DOC;

$arguments = \Docopt::handle($doc);

$firstFile  = $arguments['<firstFile>'];
$secondFile = $arguments['<secondFile>'];
$format     = $arguments['--format'];

$diff = genDiff($firstFile, $secondFile, $format);
echo $diff . PHP_EOL;
