#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use function Differ\Differ\genDiff;

$doc = <<<DOC
Generate diff

Usage:
  gendiff (-h | --help)
  gendiff (-v | --version)
  gendiff [--format <fmt>] <firstFile> <secondFile>

Options:
  -h --help         Show this screen
  -v --version      Show version
  --format <fmt>    Report format [default: stylish]
DOC;

try {
    $arguments = \Docopt::handle($doc);
} catch (Exception $e) {
    fwrite(STDERR, "Error: " . $e->getMessage() . PHP_EOL);
    exit(1);
}

if ($arguments['--help']) {
    echo $doc . PHP_EOL;
    exit(0);
}

if ($arguments['--version']) {
    $composer = json_decode(file_get_contents(__DIR__ . '/composer.json'), true);
    $version = $composer['version'] ?? '0.1.0';
    echo "gendiff $version" . PHP_EOL;
    exit(0);
}

$firstFile  = $arguments['<firstFile>'];
$secondFile = $arguments['<secondFile>'];

$diff = genDiff($firstFile, $secondFile);
echo $diff . PHP_EOL;